# Generated by Django 4.2.5 on 2023-09-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamemodel',
            options={'ordering': ['-played']},
        ),
    ]
