# Generated by Django 4.2.5 on 2023-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
