# Generated by Django 4.2.5 on 2023-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar2_hw_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
